### ISSUE TITLE
Backporting `convert_json` here

### ISSUE THREAD

**Issue by shmuhammadd** [chainsawriot/academicquacker#1]
Hi @chainsawriot ,

Thanks for the work.

I installed the package and try to run `con <- quack("igbo", db = "mydata.duckdb", db_close = TRUE)` and it returns an error below:

`Error in h(simpleError(msg, call)) : error in evaluating the argument 'value' in selecting a method for function 'dbWriteTable': 'convert_json' is not an exported object from 'namespace:academictwitteR'`

Please, can you kindly advise. 

Thanks for the community effort.

**Comment by chainsawriot** [comment]
Yeah, you need the super latest version of `academictwitteR` on Github. Please update.

**Comment by chainsawriot** [comment]
As the upstream `academictwitteR` is not on CRAN, it seems better to first backport `convert_json` from the super latest version of academictwitteR. Remove it when the upstream version is on CRAN.

**Comment by chainsawriot** [comment]
@shmuhammad2004 You don't need to have the razer edge version of `academictwitteR` now. The function `convert_json` is not back-ported here.

**Comment by shmuhammadd** [comment]
> @shmuhammad2004 You don't need to have the razer edge version of `academictwitteR` now. The function `convert_json` is not back-ported here.

@chainsawriot Thanks very much for the effort.
