### ISSUE TITLE
Error in l$contains : $ operator is invalid for atomic vectors

### ISSUE THREAD

**Issue by shmuhammadd** [chainsawriot/academicquacker#5]
H, @chainsawriot 

I tried running this

 ```

con <- quack(dir, db = "tweet.duckdb", db_close = TRUE)

con <- dbConnect(duckdb::duckdb(), dbdir = "tweets.duckdb")


```
and it returns an error:   `Error in l$contains : $ operator is invalid for atomic vectors`

I am not sure why. My `dr `is a tweets sample of four JSON files shown below:

![image](https://user-images.githubusercontent.com/38854463/128408853-6a3777b8-5d36-4d59-8f9c-479efe073d05.png)

**Comment by chainsawriot** [comment]
@shmuhammad2004 Would you mind share with me the json files?

**Comment by shmuhammadd** [comment]
@chainsawriot  yes sure. Here you go [tweets](https://we.tl/t-cqBYYlvxDT)

**Comment by shmuhammadd** [comment]
@chainsawriot  

I am now having this error ` Error: 'cli_progress_bar' is not an exported object from 'namespace:cli`'
 
After running this :  

`con <- quack("happy_emoji", db = "/lacuna/happy_emoji.duckdb" , db_close = TRUE)
`

Please, can u advise.

**Comment by chainsawriot** [comment]
@shmuhammad2004 I don't know which version of `cli` are you running, but `cli_progress_bar` is definitely [an exported object](https://cli.r-lib.org/articles/progress.html) from `cli`. Please update `cli` and restart your R session.

**Comment by chainsawriot** [comment]
Also, I want to let you know that I can't reproduce your original error.
